# [모듈 1.1] 데이터 확인

In [10]:
# Importing required libraries.
import pandas as pd
import numpy as np

pd.options.display.max_columns=30


import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
%matplotlib inline 
sns.set(color_codes=True)

data_dir = '../data'
df_claims = pd.read_csv(f"{data_dir}/claims_preprocessed.csv", index_col=0)
df_customers = pd.read_csv(f"{data_dir}/customers_preprocessed.csv", index_col=0)

## Claim 데이터 세트

In [11]:
from IPython.display import display as dp
dp(df_claims)

,incident_severity,num_vehicles_involved,num_injuries,num_witnesses,police_report_available,injury_claim,vehicle_claim,total_claim_amount,incident_month,incident_day,incident_dow,incident_hour,fraud,driver_relationship_self,driver_relationship_na,driver_relationship_spouse,driver_relationship_child,driver_relationship_other,incident_type_collision,incident_type_breakin,incident_type_theft,collision_type_front,collision_type_rear,collision_type_side,collision_type_na,authorities_contacted_police,authorities_contacted_none,authorities_contacted_fire,authorities_contacted_ambulance
policy_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,1.0,3,0,2,1.0,0,15000,15000,11,18,0,7,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,2,3,0,0.0,30000,19500,49500,2,26,1,9,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
3,0.0,2,0,1,0.0,0,10000,10000,3,18,0,13,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
4,0.0,1,0,0,0.0,0,14000,14000,1,22,1,8,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
5,0.0,2,0,2,0.0,0,12000,12000,3,30,5,6,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,1.0,2,0,0,0.0,0,12000,12000,5,14,1,11,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
4997,2.0,3,0,3,1.0,0,44000,44000,2,20,2,17,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4998,0.0,1,0,0,0.0,0,16000,16000,2,26,1,15,0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0
4999,0.0,2,0,0,0.0,0,3500,3500,2,1,4,8,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
5000,1.0,1,0,0,0.0,0,25000,25000,3,10,6,15,0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0

In [12]:
df_claims.nunique()

incident_severity                    3
num_vehicles_involved                7
num_injuries                         5
num_witnesses                        6
police_report_available              2
injury_claim                       104
vehicle_claim                       95
total_claim_amount                 182
incident_month                      12
incident_day                        31
incident_dow                         7
incident_hour                       24
fraud                                2
driver_relationship_self             2
driver_relationship_na               2
driver_relationship_spouse           2
driver_relationship_child            2
driver_relationship_other            2
incident_type_collision              2
incident_type_breakin                2
incident_type_theft                  2
collision_type_front                 2
collision_type_rear                  2
collision_type_side                  2
collision_type_na                    2
authorities_contacted_police         2
authorities_contacted_none           2
authorities_contacted_fire           2
authorities_contacted_ambulance      2
dtype: int64

## Customer 데이터 세트

In [15]:
dp(df_customers)

,customer_age,customer_education,months_as_customer,policy_deductable,policy_annual_premium,policy_liability,auto_year,num_claims_past_year,num_insurers_past_5_years,customer_gender_male,customer_gender_female,policy_state_ca,policy_state_wa,policy_state_az,policy_state_or,policy_state_nv,policy_state_id
policy_id,,,,,,,,,,,,,,,,,
1,54,2,381,750,3000,1,2019,0,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,41,3,31,750,3000,3,2017,0,3,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
3,57,3,84,750,3000,3,2014,0,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,74,4,123,750,2600,2,2018,0,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
5,39,1,34,750,3000,2,2019,0,3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4996,64,2,323,750,2450,2,2015,0,1,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4997,66,3,208,750,2850,2,2020,0,1,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4998,45,1,154,750,3000,0,2017,0,1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4999,66,4,129,750,2950,0,2015,0,1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
5000,43,4,120,750,2950,3,2019,0,1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [16]:
df_customers.nunique()

customer_age                  58
customer_education             5
months_as_customer           348
policy_deductable              7
policy_annual_premium         17
policy_liability               4
auto_year                     20
num_claims_past_year           8
num_insurers_past_5_years      5
customer_gender_male           2
customer_gender_female         2
policy_state_ca                2
policy_state_wa                2
policy_state_az                2
policy_state_or                2
policy_state_nv                2
policy_state_id                2
dtype: int64